Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/ViewModels/EmployeeViewModel.cs
using WebApp.Models;

namespace WebApp.ViewModels
{
    public class EmployeeViewModel
    {
        public Employee? Employee { get; set; }

        public List<Department>? Departments { get; set; }


    }
}

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Filters;
using WebApp.Helpers;
using WebApp.Models;
using static System.Net.Mime.MediaTypeNames;

namespace WebApp.Controllers
{    
    public class DepartmentsController : Controller
    {
        private readonly IDepartmentsRepository departmentsRepository;

        public DepartmentsController(IDepartmentsRepository departmentsRepository)
        {
            this.departmentsRepository = departmentsRepository;
        }

        [HttpGet]        
        public IActionResult Index()
        { 
            return View();
        }

        //[Route("/department-list/{filter?}")]
        //public IActionResult SearchDepartments(string? filter)
        //{   
        //    var departments = departmentsRepository.GetDepartments(filter);
        //    return PartialView("_DepartmentList", departments);
        //}

        [Route("/department-list/{filter?}")]
        public IActionResult SearchDepartments(string? filter)
        {
            return ViewComponent("DepartmentList", new { filter });
        }

        [HttpGet]        
        public IActionResult Details(int id)
        {
            var department = departmentsRepository.GetDepartmentById(id);
            if (department == null)
            {
                return View("Error", new List<string>() { "Department not found." });
            }

            return View(department);
            
        }

        [HttpPost]
        public IActionResult Edit(Department department)
        {
            if (!ModelState.IsValid)
            {
                return View("Error", ModelStateHelper.GetErrors(ModelState));
            }
            
            departmentsRepository.UpdateDepartment(department);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Create()
        {           
            return View(new Department());
        }

        [HttpPost]
        public IActionResult Create(Department department)
        {
            if (!ModelState.IsValid)
            {
                return View("Error", ModelStateHelper.GetErrors(ModelState));
            }

            departmentsRepository.AddDepartment(department);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var department = departmentsRepository.GetDepartmentById(id);
            if (department == null)
            {
                ModelState.AddModelError("id", "Department not found.");

                return View("Error", ModelStateHelper.GetErrors(ModelState));
            }

            departmentsRepository.DeleteDepartment(department);

            return RedirectToAction(nameof(Index));
        }    
        
    }
}

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Employees/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Helpers;
using WebApp.Models;
using WebApp.ViewModels;

namespace WebApp.Pages.Employees
{
    public class CreateModel : PageModel
    {
        private readonly IDepartmentsRepository departmentsRepository;
        private readonly IEmployeesRepository employeesRepository;

        public CreateModel(
            IDepartmentsRepository departmentsRepository, 
            IEmployeesRepository employeesRepository)
        {
            this.departmentsRepository = departmentsRepository;
            this.employeesRepository = employeesRepository;
        }

        [BindProperty]
        public EmployeeViewModel? EmployeeViewModel { get; set; }

        public void OnGet()
        {
            this.EmployeeViewModel = new EmployeeViewModel();
            this.EmployeeViewModel.Employee = new Employee();
            this.EmployeeViewModel.Departments = departmentsRepository.GetDepartments();
        }

        public IActionResult OnPost() 
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelStateHelper.GetErrors(this.ModelState);   
                return RedirectToPage("/Error", new { errors});
            }

            if (this.EmployeeViewModel is not null && this.EmployeeViewModel.Employee is not null)
            {
                employeesRepository.AddEmployee(this.EmployeeViewModel.Employee);
            }

            return RedirectToPage("Index");
        }
    }
}

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Employees/DepartmentEmployees.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Models;

namespace WebApp.Pages.Employees
{
    public class DepartmentEmployeesModel : PageModel
    {
        private readonly IDepartmentsRepository departmentsRepository;

        public DepartmentEmployeesModel(IDepartmentsRepository departmentsRepository)
        {
            this.departmentsRepository = departmentsRepository;
        }

        public string? DepartmentName { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? DepartmentId { get; set; }

        public void OnGet()
        {
            if (DepartmentId.HasValue)
            {
                var department = departmentsRepository.GetDepartmentById(DepartmentId.Value);
                DepartmentName = department?.Name;
            }
        }
    }
}

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Employees/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Helpers;
using WebApp.Models;
using WebApp.ViewModels;

namespace WebApp.Pages.Employees
{
    public class EditModel : PageModel
    {
        private readonly IEmployeesRepository employeesRepository;
        private readonly IDepartmentsRepository departmentsRepository;

        public EditModel(IEmployeesRepository employeesRepository, IDepartmentsRepository departmentsRepository)
        {
            this.employeesRepository = employeesRepository;
            this.departmentsRepository = departmentsRepository;
        }

        [BindProperty]
        public EmployeeViewModel? EmployeeViewModel { get; set; }

        public void OnGet(int id)
        {
            this.EmployeeViewModel = new EmployeeViewModel();
            this.EmployeeViewModel.Employee = employeesRepository.GetEmployeeById(id);
            this.EmployeeViewModel.Departments = departmentsRepository.GetDepartments();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelStateHelper.GetErrors(ModelState);
                return RedirectToPage("/Error", new { errors });
            }

            if (EmployeeViewModel is not null && EmployeeViewModel.Employee != null)
            {
                employeesRepository.UpdateEmployee(EmployeeViewModel.Employee);
            }

            return RedirectToPage("Index");
        }

        public IActionResult OnPostDeleteEmplopyee(int id)
        {
            var employee = employeesRepository.GetEmployeeById(id);
            if (employee == null)
            {
                ModelState.AddModelError("id", "Employee not found");

                var errors = ModelStateHelper.GetErrors(ModelState);
                return RedirectToPage("/Error", new { errors });
            }

            employeesRepository.DeleteEmployee(employee);

            return RedirectToPage("Index");
        }

    }
}

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Employees/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Filters;
using WebApp.Models;

namespace WebApp.Pages.Employees
{    
    public class IndexModel : PageModel
    {        
        public List<Employee>? Employees { get; set; }

        public void OnGet()
        {
            //this.Employees = EmployeesRepository.GetEmployees();
        }        

        public IActionResult OnGetSearchEmployeeResult(string? filter)
        {
            return ViewComponent("EmployeeList", new { filter });
        }
    }
}

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Shared/Components/EmployeeList/EmployeeListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Pages.Shared.Components.EmployeeList
{
    public class EmployeeListViewComponent : ViewComponent
    {
        private readonly IEmployeesRepository employeesRepository;

        public EmployeeListViewComponent(IEmployeesRepository employeesRepository)
        {
            this.employeesRepository = employeesRepository;
        }

        public IViewComponentResult Invoke(string? filter, int? departmentId)
        {
            return View(employeesRepository.GetEmployees(filter, departmentId));
        }
    }
}

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Employees/Create.cshtml
@page "/create-employees"
@model WebApp.Pages.Employees.CreateModel
@{
    ViewBag.Action = "create";
}

@section title_section {
    <h3>Add Employee</h3>
}

<partial name="_EmployeeDetail" , model="Model.EmployeeViewModel" />

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Employees/DepartmentEmployees.cshtml
@page "{departmentId:int}"

@model WebApp.Pages.Employees.DepartmentEmployeesModel
@{
}

@section title_section
{
    <h3>Employees of Department: @Model.DepartmentName</h3>
}
<table class="table table-striped">
    <thread>
        <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Salary</th>
            <th>Department</th>
            <th></th>
        </tr>
    </thread>
    <tbody id="employee-list">        
        
        <vc:employee-list filter=""  department-id="@Model.DepartmentId"></vc:employee-list>
    </tbody>
</table>

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Employees/Edit.cshtml
@page "{id:int}"
@model WebApp.Pages.Employees.EditModel
@{
    ViewBag.Action = "edit";
}

@section title_section {
    <h3>Edit Employee</h3>
}

<partial name="_EmployeeDetail", model="Model.EmployeeViewModel" />

<form 
    name="deleteEmployheeForm" 
    method="post" 
    asp-page="/employees/edit"
    asp-route-id="@Model.EmployeeViewModel.Employee.Id"
    asp-page-handler="DeleteEmplopyee">

    <button type="submit" id="delete-employee" class="btn btn-danger">Delete</button>

</form>


@section scripts
{
    <script>
        document.querySelector("#delete-employee").addEventListener("click",  (event) => {
            event.preventDefault(); // Prevent the default form submission

            const employeeName = '@Model.EmployeeViewModel.Employee.Name';

            const userComfirmation = confirm(`Are you sure you want to delete the employee: ${employeeName}`);

            if (userComfirmation) {
                document.forms["deleteEmployheeForm"].submit();
            }
        });
    </script>
}

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Employees/Index.cshtml
@page
@model WebApp.Pages.Employees.IndexModel

@section title_section
{
    <h3>Employees</h3>
}

<partial name="_SearchBar" />

<table class="table table-striped">
    <thread>
        <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Salary</th>
            <th>Department</th>
            <th></th>
        </tr>
    </thread>
    <tbody id="employee-list">
        @* @await Component.InvokeAsync("EmployeeList") *@
    </tbody>
</table>

<br />
<a class="btn btn-primary" 
    asp-page="/employees/create">Add</a>

@section scripts
{
    <script>
        loadEmployees('');

        document.querySelector("#search-button").addEventListener("click", async () => {
            var filter = document.querySelector("#search-filter").value;

            loadEmployees(filter);
        });

        async function loadEmployees(filter){
            var response = await fetch(`/employees?filter=${filter}&handler=SearchEmployeeResult`);
            var html = await response.text();

            document.querySelector("#employee-list").innerHTML = html;
        }
    </script>
}

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Employees/_EmployeeDetail.cshtml
@model EmployeeViewModel

@if (Model is not null && Model.Employee is not null)
{
    <form method="post">
        <div asp-validation-summary="All" class="text-danger">
        </div>

        @if (ViewBag.Action == "edit"){
            <input asp-for="Employee.Id" />
        }

        <div class="row mb-3">
            <div class="col-2">
                <label class="col-form-label" asp-for="Employee.Name"></label>
            </div>
            <div class="col-6">
                <input class="form-control" asp-for="Employee.Name" />
                <span class="text-danger" asp-validation-for="Employee.Name"></span>
            </div>            
        </div>

        <div class="row mb-3">
            <div class="col-2">
                <label class="col-form-label" asp-for="Employee.Position"></label>
            </div>
            <div class="col-6">
                <input asp-for="Employee.Position" class="form-control" />
                <span class="text-danger" asp-validation-for="Employee.Position"></span>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-2">
                <label class="col-form-label" asp-for="Employee.Salary"></label>
            </div>
            <div class="col-6">
                <input asp-for="Employee.Salary" class="form-control" />
                <span class="text-danger" asp-validation-for="Employee.Salary"></span>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-2">
                <label class="col-form-label" asp-for="Employee.DepartmentId"></label>
            </div>
            <div class="col-6">
                <select class="form-control"
                        asp-for="Employee.DepartmentId"
                        asp-items='Model.Departments.Select(
                            x => new SelectListItem() {
                                Text = x.Name,
                                Value = x.Id.ToString(),
                                Selected=(ViewBag.Action == "edit" && x.Id == Model.Employee.DepartmentId)} )'>

                    @if (ViewBag.Action == "create")
                    {
                        <option selected value="0">-- Please Select --</option>
                    }
                    else
                    {
                        <option value="0">-- Please Select --</option>
                    }
                </select>
                <span class="text-danger" asp-validation-for="Employee.DepartmentId"></span>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-2">
                <button type='submit' class="btn btn-primary">Save</button>
                &nbsp;&nbsp;
                <a asp-page="/employees/index" class="btn btn-primary">Cancel</a>
            </div>
            <div class="col-4">
                
            </div>
        </div>
    </form>
}

Section19_MvcRazorFilters/158_FilterScopes/FilterScopes/WebApp/Pages/Employees/_EmployeeListItem.cshtml

@model Employee

@if (Model is not null)
{
    <tr>
        <td>@Model.Name</td>
        <td>@Model.Position</td>
        <td>@Model.Salary</td>
        <td><a class="btn btn-link" 
                asp-controller="Departments"
                asp-action="Details"
                asp-route-id="@Model.DepartmentId">@Model.Department?.Name</a></td>
        <td><a class="btn btn-link" 
                asp-page="/employees/edit"
                asp-route-id="@Model.Id">Edit</a></td>
    </tr>
}